# coding: utf-8

"""
    Reepay Checkout API

    Reepay Checkout REST API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.session_info_api import SessionInfoApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSessionInfoApi(unittest.TestCase):
    """SessionInfoApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.session_info_api.SessionInfoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_session(self):
        """Test case for get_session

        Get session info  # noqa: E501
        """
        pass

    def test_get_sessions(self):
        """Test case for get_sessions

        Get sessions by relation type and handle  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
