# coding: utf-8

"""
    Reepay Checkout API

    Reepay Checkout REST API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.applepay_payment_request_dto import ApplepayPaymentRequestDto  # noqa: E501
from swagger_client.rest import ApiException


class TestApplepayPaymentRequestDto(unittest.TestCase):
    """ApplepayPaymentRequestDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplepayPaymentRequestDto(self):
        """Test ApplepayPaymentRequestDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.applepay_payment_request_dto.ApplepayPaymentRequestDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
