# coding: utf-8

"""
    Reepay Checkout API

    Reepay Checkout REST API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.resurs_payment_method_dto import ResursPaymentMethodDto  # noqa: E501
from swagger_client.rest import ApiException


class TestResursPaymentMethodDto(unittest.TestCase):
    """ResursPaymentMethodDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResursPaymentMethodDto(self):
        """Test ResursPaymentMethodDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.resurs_payment_method_dto.ResursPaymentMethodDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
