# coding: utf-8

"""
    Reepay Checkout API

    Reepay Checkout REST API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.create_recurring_session import CreateRecurringSession  # noqa: E501
from swagger_client.rest import ApiException


class TestCreateRecurringSession(unittest.TestCase):
    """CreateRecurringSession unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateRecurringSession(self):
        """Test CreateRecurringSession"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.create_recurring_session.CreateRecurringSession()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
