# coding: utf-8

"""
    Reepay Checkout API

    Reepay Checkout REST API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.subscription_add_on import SubscriptionAddOn  # noqa: E501
from swagger_client.rest import ApiException


class TestSubscriptionAddOn(unittest.TestCase):
    """SubscriptionAddOn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubscriptionAddOn(self):
        """Test SubscriptionAddOn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.subscription_add_on.SubscriptionAddOn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
