# coding: utf-8

"""
    Reepay Checkout API

    Reepay Checkout REST API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.signup_api import SignupApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSignupApi(unittest.TestCase):
    """SignupApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.signup_api.SignupApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_signup_page(self):
        """Test case for create_signup_page

        Create signup page  # noqa: E501
        """
        pass

    def test_delete_signup_page(self):
        """Test case for delete_signup_page

        Delete signup page  # noqa: E501
        """
        pass

    def test_get_signup_page(self):
        """Test case for get_signup_page

        Get signup page  # noqa: E501
        """
        pass

    def test_get_signup_page_signup(self):
        """Test case for get_signup_page_signup

        Get signup page signup data  # noqa: E501
        """
        pass

    def test_get_signup_pages(self):
        """Test case for get_signup_pages

        Get signup pages  # noqa: E501
        """
        pass

    def test_update_signup_page(self):
        """Test case for update_signup_page

        Update signup page  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
