# coding: utf-8

"""
    Reepay Checkout API

    Reepay Checkout REST API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CreatePGWSession(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'payment_type': 'str',
        'return_url': 'str'
    }

    attribute_map = {
        'payment_type': 'paymentType',
        'return_url': 'returnUrl'
    }

    def __init__(self, payment_type=None, return_url=None):  # noqa: E501
        """CreatePGWSession - a model defined in Swagger"""  # noqa: E501

        self._payment_type = None
        self._return_url = None
        self.discriminator = None

        self.payment_type = payment_type
        if return_url is not None:
            self.return_url = return_url

    @property
    def payment_type(self):
        """Gets the payment_type of this CreatePGWSession.  # noqa: E501


        :return: The payment_type of this CreatePGWSession.  # noqa: E501
        :rtype: str
        """
        return self._payment_type

    @payment_type.setter
    def payment_type(self, payment_type):
        """Sets the payment_type of this CreatePGWSession.


        :param payment_type: The payment_type of this CreatePGWSession.  # noqa: E501
        :type: str
        """
        if payment_type is None:
            raise ValueError("Invalid value for `payment_type`, must not be `None`")  # noqa: E501
        allowed_values = ["CARD", "APPLEPAY", "GOOGLEPAY", "PAYPAL", "VIABILL", "MOBILEPAY", "MOBILEPAY_SUBSCRIPTION", "KLARNA_PAY_NOW", "KLARNA_PAY_LATER", "RESURS", "MANUAL"]  # noqa: E501
        if payment_type not in allowed_values:
            raise ValueError(
                "Invalid value for `payment_type` ({0}), must be one of {1}"  # noqa: E501
                .format(payment_type, allowed_values)
            )

        self._payment_type = payment_type

    @property
    def return_url(self):
        """Gets the return_url of this CreatePGWSession.  # noqa: E501


        :return: The return_url of this CreatePGWSession.  # noqa: E501
        :rtype: str
        """
        return self._return_url

    @return_url.setter
    def return_url(self, return_url):
        """Sets the return_url of this CreatePGWSession.


        :param return_url: The return_url of this CreatePGWSession.  # noqa: E501
        :type: str
        """

        self._return_url = return_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreatePGWSession, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreatePGWSession):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
