# coding: utf-8

"""
    Reepay Checkout API

    Reepay Checkout REST API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CreateResursSession(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'payment_method_id': 'str',
        'return_url': 'str'
    }

    attribute_map = {
        'payment_method_id': 'paymentMethodId',
        'return_url': 'returnUrl'
    }

    def __init__(self, payment_method_id=None, return_url=None):  # noqa: E501
        """CreateResursSession - a model defined in Swagger"""  # noqa: E501

        self._payment_method_id = None
        self._return_url = None
        self.discriminator = None

        if payment_method_id is not None:
            self.payment_method_id = payment_method_id
        if return_url is not None:
            self.return_url = return_url

    @property
    def payment_method_id(self):
        """Gets the payment_method_id of this CreateResursSession.  # noqa: E501


        :return: The payment_method_id of this CreateResursSession.  # noqa: E501
        :rtype: str
        """
        return self._payment_method_id

    @payment_method_id.setter
    def payment_method_id(self, payment_method_id):
        """Sets the payment_method_id of this CreateResursSession.


        :param payment_method_id: The payment_method_id of this CreateResursSession.  # noqa: E501
        :type: str
        """

        self._payment_method_id = payment_method_id

    @property
    def return_url(self):
        """Gets the return_url of this CreateResursSession.  # noqa: E501


        :return: The return_url of this CreateResursSession.  # noqa: E501
        :rtype: str
        """
        return self._return_url

    @return_url.setter
    def return_url(self, return_url):
        """Sets the return_url of this CreateResursSession.


        :param return_url: The return_url of this CreateResursSession.  # noqa: E501
        :type: str
        """

        self._return_url = return_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateResursSession, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateResursSession):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
