# coding: utf-8

"""
    Reepay Checkout API

    Reepay Checkout REST API  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class TransactionInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'currency_code': 'str',
        'total_price_status': 'str',
        'total_price': 'str',
        'country_code': 'str'
    }

    attribute_map = {
        'currency_code': 'currencyCode',
        'total_price_status': 'totalPriceStatus',
        'total_price': 'totalPrice',
        'country_code': 'countryCode'
    }

    def __init__(self, currency_code=None, total_price_status=None, total_price=None, country_code=None):  # noqa: E501
        """TransactionInfo - a model defined in Swagger"""  # noqa: E501

        self._currency_code = None
        self._total_price_status = None
        self._total_price = None
        self._country_code = None
        self.discriminator = None

        if currency_code is not None:
            self.currency_code = currency_code
        if total_price_status is not None:
            self.total_price_status = total_price_status
        if total_price is not None:
            self.total_price = total_price
        if country_code is not None:
            self.country_code = country_code

    @property
    def currency_code(self):
        """Gets the currency_code of this TransactionInfo.  # noqa: E501


        :return: The currency_code of this TransactionInfo.  # noqa: E501
        :rtype: str
        """
        return self._currency_code

    @currency_code.setter
    def currency_code(self, currency_code):
        """Sets the currency_code of this TransactionInfo.


        :param currency_code: The currency_code of this TransactionInfo.  # noqa: E501
        :type: str
        """

        self._currency_code = currency_code

    @property
    def total_price_status(self):
        """Gets the total_price_status of this TransactionInfo.  # noqa: E501


        :return: The total_price_status of this TransactionInfo.  # noqa: E501
        :rtype: str
        """
        return self._total_price_status

    @total_price_status.setter
    def total_price_status(self, total_price_status):
        """Sets the total_price_status of this TransactionInfo.


        :param total_price_status: The total_price_status of this TransactionInfo.  # noqa: E501
        :type: str
        """

        self._total_price_status = total_price_status

    @property
    def total_price(self):
        """Gets the total_price of this TransactionInfo.  # noqa: E501


        :return: The total_price of this TransactionInfo.  # noqa: E501
        :rtype: str
        """
        return self._total_price

    @total_price.setter
    def total_price(self, total_price):
        """Sets the total_price of this TransactionInfo.


        :param total_price: The total_price of this TransactionInfo.  # noqa: E501
        :type: str
        """

        self._total_price = total_price

    @property
    def country_code(self):
        """Gets the country_code of this TransactionInfo.  # noqa: E501


        :return: The country_code of this TransactionInfo.  # noqa: E501
        :rtype: str
        """
        return self._country_code

    @country_code.setter
    def country_code(self, country_code):
        """Sets the country_code of this TransactionInfo.


        :param country_code: The country_code of this TransactionInfo.  # noqa: E501
        :type: str
        """

        self._country_code = country_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TransactionInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TransactionInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
